const DB= [
  // EASY: Months, Days, Seasons & Times
  ["january","easy"],["march","easy"],["april","easy"],["may","easy"],["june","easy"],
  ["july","easy"],["august","easy"],["september","easy"],["october","easy"],["november","easy"],
  ["december","easy"],["monday","easy"],["tuesday","easy"],["thursday","easy"],["friday","easy"],
  ["saturday","easy"],["sunday","easy"],["spring","easy"],["summer","easy"],["autumn","easy"],
  ["winter","easy"],["morning","easy"],["afternoon","easy"],["evening","easy"],["midnight","easy"],
  ["sunrise","easy"],["sunset","easy"],["weekend","easy"],["weekday","easy"],["fortnight","easy"],

  // EASY: Numbers, Ordinals & Math
  ["zero","easy"],["first","easy"],["second","easy"],["third","easy"],["fourth","easy"],
  ["fifth","easy"],["sixth","easy"],["seventh","easy"],["eighth","easy"],["ninth","easy"],
  ["tenth","easy"],["eleventh","easy"],["twelfth","easy"],["thirteenth","easy"],["fourteenth","easy"],
  ["fifteenth","easy"],["sixteenth","easy"],["seventeenth","easy"],["eighteenth","easy"],["nineteenth","easy"],
  ["twentieth","easy"],["thirtieth","easy"],["fiftieth","easy"],["hundredth","easy"],["thousandth","easy"],
  ["million","easy"],["billion","easy"],["quarter","easy"],["half","easy"],["dozen","easy"],
  ["fraction","easy"],["percentage","easy"],["addition","easy"],["subtraction","easy"],["multiply","easy"],

  // EASY: Common IELTS Names
  ["william","easy"],["elizabeth","easy"],["james","easy"],["sarah","easy"],["george","easy"],
  ["margaret","easy"],["charles","easy"],["joseph","easy"],["thomas","easy"],["alice","easy"],
  ["henry","easy"],["florence","easy"],["arthur","easy"],["beatrice","easy"],["edward","easy"],
  ["charlotte","easy"],["david","easy"],["emily","easy"],["richard","easy"],["victoria","easy"],
  ["michael","easy"],["alexander","easy"],["isabella","easy"],["robert","easy"],["olivia","easy"],
  ["daniel","easy"],["sophia","easy"],["matthew","easy"],["amelia","easy"],["andrew","easy"],
  ["joshua","easy"],["kevin","easy"],["chloe","easy"],["brian","easy"],["grace","easy"],
  ["jason","easy"],["justin","easy"],["ryan","easy"],["megan","easy"],["aaron","easy"],

  // EASY: Addresses, Streets & Basic Places
  ["avenue","easy"],["boulevard","easy"],["street","easy"],["road","easy"],["lane","easy"],
  ["drive","easy"],["court","easy"],["alley","easy"],["terrace","easy"],["highway","easy"],
  ["freeway","easy"],["expressway","easy"],["motorway","easy"],["turnpike","easy"],["plaza","easy"],
  ["square","easy"],["promenade","easy"],["arcade","easy"],["bypass","easy"],["esplanade","easy"],
  ["north","easy"],["south","easy"],["east","easy"],["west","easy"],["northeast","easy"],
  ["southwest","easy"],["apartment","easy"],["village","easy"],["town","easy"],["city","easy"],

  // MEDIUM: Countries, Cities & Geography
  ["australia","medium"],["germany","medium"],["france","medium"],["italy","medium"],["spain","medium"],
  ["mexico","medium"],["russia","medium"],["egypt","medium"],["england","medium"],["scotland","medium"],
  ["wales","medium"],["ireland","medium"],["birmingham","medium"],["manchester","medium"],["liverpool","medium"],
  ["edinburgh","medium"],["glasgow","medium"],["melbourne","medium"],["brisbane","medium"],["auckland","medium"],
  ["wellington","medium"],["toronto","medium"],["vancouver","medium"],["washington","medium"],["chicago","medium"],
  ["seattle","medium"],["yorkshire","medium"],["lancashire","medium"],["cornwall","medium"],["cumbria","medium"],
  ["surrey","medium"],["sussex","medium"],["norfolk","medium"],["suffolk","medium"],["oxfordshire","medium"],
  ["gloucestershire","medium"],["warwickshire","medium"],["nottinghamshire","medium"],["cambridgeshire","medium"],["continent","medium"],

  // MEDIUM: Academic & Universities
  ["abstract","medium"],["academy","medium"],["accreditation","medium"],["administration","medium"],["admission","medium"],
  ["algebra","medium"],["alumni","medium"],["analysis","medium"],["anthropology","medium"],["appendix","medium"],
  ["architecture","medium"],["archive","medium"],["article","medium"],["assessment","medium"],["assignment","medium"],
  ["astronomy","medium"],["attendance","medium"],["auditorium","medium"],["bachelor","medium"],["bibliography","medium"],
  ["biology","medium"],["bursary","medium"],["calculus","medium"],["campus","medium"],["canteen","medium"],
  ["certificate","medium"],["chancellor","medium"],["chemistry","medium"],["citation","medium"],["clinic","medium"],
  ["cohort","medium"],["college","medium"],["colloquium","medium"],["comprehensive","medium"],["compulsory","medium"],
  ["conference","medium"],["conservatory","medium"],["consortium","medium"],["coursework","medium"],["credential","medium"],
  ["deadline","medium"],["dean","medium"],["debate","medium"],["deferral","medium"],["degree","medium"],
  ["department","medium"],["diagram","medium"],["dictionary","medium"],["diploma","medium"],["director","medium"],
  ["discourse","medium"],["dissertation","medium"],["distinction","medium"],["doctorate","medium"],["dormitory","medium"],
  ["ecology","medium"],["economics","medium"],["elective","medium"],["elementary","medium"],["eligibility","medium"],
  ["encyclopedia","medium"],["engineering","medium"],["enrollment","medium"],["entrance","medium"],["essay","medium"],
  ["ethics","medium"],["evaluation","medium"],["examination","medium"],["exchange","medium"],["exhibition","medium"],
  ["experiment","medium"],["extension","medium"],["extracurricular","medium"],["facility","medium"],["faculty","medium"],
  ["fellowship","medium"],["fieldwork","medium"],["foundation","medium"],["framework","medium"],["freshman","medium"],
  ["funding","medium"],["gallery","medium"],["genetics","medium"],["geography","medium"],["geology","medium"],
  ["geometry","medium"],["glossary","medium"],["graduate","medium"],["grant","medium"],["guideline","medium"],
  ["gymnasium","medium"],["handbook","medium"],["harvard","medium"],["history","medium"],["honorarium","medium"],
  ["horticulture","medium"],["housing","medium"],["humanities","medium"],["hypothesis","medium"],["illustration","medium"],
  ["index","medium"],["induction","medium"],["infrastructure","medium"],["innovation","medium"],["institute","medium"],
  ["instruction","medium"],["instructor","medium"],["integration","medium"],["interactive","medium"],["interdisciplinary","medium"],
  ["intermediate","medium"],["internship","medium"],["interview","medium"],["investigation","medium"],["itinerary","medium"],
  ["journal","medium"],["journalism","medium"],["junior","medium"],["knowledge","medium"],["language","medium"],
  ["learning","medium"],["lecture","medium"],["librarian","medium"],["library","medium"],["linguistics","medium"],
  ["literacy","medium"],["literature","medium"],["logic","medium"],["logistics","medium"],["magazine","medium"],
  ["major","medium"],["management","medium"],["manual","medium"],["manuscript","medium"],["marketing","medium"],
  ["mathematics","medium"],["matriculation","medium"],["mechanics","medium"],["medicine","medium"],["mentor","medium"],
  ["methodology","medium"],["microbiology","medium"],["midterm","medium"],["module","medium"],["monograph","medium"],
  ["motivation","medium"],["museum","medium"],["musicology","medium"],["narrative","medium"],["navigation","medium"],
  ["neurology","medium"],["notation","medium"],["nursing","medium"],["nutrition","medium"],["objective","medium"],
  ["observatory","medium"],["oceanography","medium"],["orientation","medium"],["outline","medium"],["oxford","medium"],
  ["paleontology","medium"],["paragraph","medium"],["parameter","medium"],["pathology","medium"],["pedagogy","medium"],
  ["penalty","medium"],["perception","medium"],["performance","medium"],["periodical","medium"],["perspective","medium"],
  ["pharmacology","medium"],["phenomenology","medium"],["phonetics","medium"],["photography","medium"],["physics","medium"],
  ["physiology","medium"],["placement","medium"],["plagiarism","medium"],["portfolio","medium"],["postgraduate","medium"],
  ["practical","medium"],["prerequisite","medium"],["presentation","medium"],["primary","medium"],["principle","medium"],
  ["probation","medium"],["procedure","medium"],["proceeding","medium"],["profile","medium"],["program","medium"],
  ["project","medium"],["promotion","medium"],["proofread","medium"],["proposal","medium"],["prospectus","medium"],
  ["protocol","medium"],["prototype","medium"],["publication","medium"],["publisher","medium"],["punctuation","medium"],
  ["qualification","medium"],["qualitative","medium"],["quantitative","medium"],["quotation","medium"],["reasoning","medium"],
  ["reference","medium"],["register","medium"],["registrar","medium"],["registration","medium"],["regulation","medium"],
  ["rehearsal","medium"],["reimbursement","medium"],["rejection","medium"],["renewable","medium"],["requirement","medium"],
  ["research","medium"],["reservation","medium"],["residence","medium"],["resolution","medium"],["resource","medium"],
  ["response","medium"],["restriction","medium"],["resume","medium"],["retention","medium"],["review","medium"],
  ["revision","medium"],["robotics","medium"],["roster","medium"],["rubric","medium"],["sabbatical","medium"],
  ["salary","medium"],["schedule","medium"],["scholarship","medium"],["science","medium"],["secondary","medium"],
  ["semester","medium"],["seminar","medium"],["senate","medium"],["senior","medium"],["sequence","medium"],
  ["session","medium"],["simulation","medium"],["sociology","medium"],["software","medium"],["sophomore","medium"],
  ["specialization","medium"],["specification","medium"],["spectrum","medium"],["sponsor","medium"],["spreadsheet","medium"],
  ["stadium","medium"],["statistic","medium"],["strategy","medium"],["structure","medium"],["student","medium"],
  ["studio","medium"],["submission","medium"],["subsidiary","medium"],["subsidy","medium"],["summary","medium"],
  ["supervisor","medium"],["supplement","medium"],["syllabus","medium"],["symbol","medium"],["symposium","medium"],
  ["synthesis","medium"],["system","medium"],["tablet","medium"],["talent","medium"],["taxonomy","medium"],
  ["technology","medium"],["telecommunication","medium"],["template","medium"],["tenure","medium"],["terminal","medium"],
  ["textbook","medium"],["theater","medium"],["theology","medium"],["theorem","medium"],["theory","medium"],
  ["thesis","medium"],["timeline","medium"],["timetable","medium"],["topic","medium"],["tournament","medium"],
  ["tradition","medium"],["trainee","medium"],["training","medium"],["transcript","medium"],["transfer","medium"],
  ["translation","medium"],["transmission","medium"],["transportation","medium"],["tuition","medium"],["tutor","medium"],
  ["tutorial","medium"],["undergraduate","medium"],["union","medium"],["university","medium"],["update","medium"],
  ["upgrade","medium"],["vacancy","medium"],["vacation","medium"],["vaccination","medium"],["validity","medium"],
  ["valuation","medium"],["variable","medium"],["variation","medium"],["vehicle","medium"],["vendor","medium"],
  ["venue","medium"],["verification","medium"],["version","medium"],["veterinary","medium"],["video","medium"],
  ["violation","medium"],["violence","medium"],["virus","medium"],["visa","medium"],["vision","medium"],
  ["vocabulary","medium"],["vocation","medium"],["volume","medium"],["volunteer","medium"],["voucher","medium"],
  ["warehouse","medium"],["welfare","medium"],["wildlife","medium"],["withdrawal","medium"],["workshop","medium"],
  ["zoology","medium"],

  // MEDIUM: Jobs & Professions
  ["accountant","medium"],["architect","medium"],["engineer","medium"],["scientist","medium"],["journalist","medium"],
  ["manager","medium"],["director","medium"],["assistant","medium"],["supervisor","medium"],["executive","medium"],
  ["physician","medium"],["surgeon","medium"],["pediatrician","medium"],["dermatologist","medium"],["cardiologist","medium"],
  ["neurologist","medium"],["psychiatrist","medium"],["oncologist","medium"],["radiologist","medium"],["anesthesiologist","medium"],
  ["optician","medium"],["dentist","medium"],["orthodontist","medium"],["hygienist","medium"],["therapist","medium"],
  ["physiotherapist","medium"],["chiropractor","medium"],["acupuncturist","medium"],["herbalist","medium"],["pharmacist","medium"],
  ["paramedic","medium"],["midwife","medium"],["developer","medium"],["designer","medium"],["plumber","medium"],
  ["electrician","medium"],["carpenter","medium"],["mechanic","medium"],["technician","medium"],["consultant","medium"],

  // MEDIUM: Health & Medicine
  ["dietary","medium"],["digestion","medium"],["respiratory","medium"],["cardiovascular","medium"],["muscular","medium"],
  ["skeletal","medium"],["nervous","medium"],["immune","medium"],["endocrine","medium"],["reproductive","medium"],
  ["urinary","medium"],["lymphatic","medium"],["anatomy","medium"],["epidemiology","medium"],["virology","medium"],
  ["bacteriology","medium"],["parasitology","medium"],["sanitation","medium"],["quarantine","medium"],["isolation","medium"],
  ["immunization","medium"],["antibiotic","medium"],["antiseptic","medium"],["analgesic","medium"],["anesthetic","medium"],
  ["sedative","medium"],["stimulant","medium"],["antidepressant","medium"],["prescription","medium"],["dosage","medium"],
  ["overdose","medium"],["allergic","medium"],["chronic","medium"],["acute","medium"],["contagious","medium"],
  ["infectious","medium"],["hereditary","medium"],["congenital","medium"],["terminal","medium"],["malignant","medium"],
  ["benign","medium"],["tumor","medium"],["cancer","medium"],["diabetes","medium"],["asthma","medium"],
  ["arthritis","medium"],["rheumatism","medium"],["stroke","medium"],["fracture","medium"],["sprain","medium"],
  ["strain","medium"],["dislocation","medium"],["scald","medium"],["wound","medium"],["scar","medium"],
  ["bruise","medium"],["blister","medium"],["rash","medium"],["ulcer","medium"],["inflammation","medium"],
  ["infection","medium"],["fever","medium"],["cough","medium"],["sneeze","medium"],["fatigue","medium"],
  ["nausea","medium"],["vomit","medium"],["dizzy","medium"],["faint","medium"],["unconscious","medium"],
  ["coma","medium"],["paralysis","medium"],["handicap","medium"],["disability","medium"],["therapy","medium"],
  ["rehabilitation","medium"],["surgery","medium"],["operation","medium"],["transplant","medium"],["implant","medium"],
  ["amputation","medium"],["biopsy","medium"],["autopsy","medium"],["ultrasound","medium"],["plasma","medium"],
  ["serum","medium"],["tissue","medium"],["organ","medium"],["muscle","medium"],["bone","medium"],
  ["joint","medium"],["cartilage","medium"],["ligament","medium"],["tendon","medium"],["nerve","medium"],
  ["brain","medium"],["heart","medium"],["lung","medium"],["liver","medium"],["kidney","medium"],
  ["stomach","medium"],["intestine","medium"],["bowel","medium"],["bladder","medium"],["gland","medium"],
  ["hormone","medium"],["enzyme","medium"],["protein","medium"],["vitamin","medium"],["mineral","medium"],
  ["fat","medium"],["calorie","medium"],["diet","medium"],["obesity","medium"],["anorexia","medium"],
  ["bulimia","medium"],["starvation","medium"],["malnutrition","medium"],["fitness","medium"],["exercise","medium"],
  ["aerobic","medium"],["anaerobic","medium"],["meditation","medium"],["relaxation","medium"],["massage","medium"],
  ["sauna","medium"],["jacuzzi","medium"],["treadmill","medium"],["dumbbell","medium"],["barbell","medium"],
  ["weight","medium"],["sweat","medium"],["perspiration","medium"],["stamina","medium"],["endurance","medium"],
  ["strength","medium"],["flexibility","medium"],["agility","medium"],["balance","medium"],["coordination","medium"],

  // MEDIUM: Environment, Technology & Science
  ["atmosphere","medium"],["biosphere","medium"],["ecosystem","medium"],["habitat","medium"],["biodiversity","medium"],
  ["extinction","medium"],["endangered","medium"],["species","medium"],["predator","medium"],["prey","medium"],
  ["carnivore","medium"],["herbivore","medium"],["omnivore","medium"],["mammal","medium"],["reptile","medium"],
  ["amphibian","medium"],["terrestrial","medium"],["aquatic","medium"],["marine","medium"],["coastal","medium"],
  ["inland","medium"],["continental","medium"],["tropical","medium"],["subtropical","medium"],["temperate","medium"],
  ["polar","medium"],["arctic","medium"],["antarctic","medium"],["glacier","medium"],["iceberg","medium"],
  ["avalanche","medium"],["blizzard","medium"],["cyclone","medium"],["typhoon","medium"],["monsoon","medium"],
  ["drought","medium"],["flood","medium"],["famine","medium"],["earthquake","medium"],["tsunami","medium"],
  ["volcano","medium"],["eruption","medium"],["crater","medium"],["lava","medium"],["magma","medium"],
  ["crust","medium"],["mantle","medium"],["core","medium"],["tectonic","medium"],["plate","medium"],
  ["fault","medium"],["fossil","medium"],["fuel","medium"],["coal","medium"],["petroleum","medium"],
  ["diesel","medium"],["petrol","medium"],["solar","medium"],["lunar","medium"],["wind","medium"],
  ["hydro","medium"],["geothermal","medium"],["biomass","medium"],["renewable","medium"],["sustainable","medium"],
  ["alternative","medium"],["efficient","medium"],["panel","medium"],["turbine","medium"],["generator","medium"],
  ["battery","medium"],["grid","medium"],["emission","medium"],["exhaust","medium"],["tailpipe","medium"],
  ["chimney","medium"],["smokestack","medium"],["greenhouse","medium"],["warming","medium"],["climate","medium"],
  ["change","medium"],["carbon","medium"],["dioxide","medium"],["footprint","medium"],["offset","medium"],
  ["credit","medium"],["ozone","medium"],["layer","medium"],["depletion","medium"],["acid","medium"],
  ["rain","medium"],["smog","medium"],["haze","medium"],["particulate","medium"],["filter","medium"],
  ["catalytic","medium"],["converter","medium"],["purify","medium"],["treat","medium"],["recycle","medium"],
  ["reuse","medium"],["reduce","medium"],["compost","medium"],["incinerate","medium"],["landfill","medium"],
  ["dump","medium"],["litter","medium"],["trash","medium"],["garbage","medium"],["rubbish","medium"],
  ["waste","medium"],["sewage","medium"],["contaminate","medium"],["pollute","medium"],["degrade","medium"],
  ["erode","medium"],["deforestation","medium"],["desertification","medium"],["soil","medium"],["topsoil","medium"],
  ["clay","medium"],["silt","medium"],["sand","medium"],["gravel","medium"],["rock","medium"],
  ["stone","medium"],["pebble","medium"],["boulder","medium"],["mineral","medium"],["ore","medium"],
  ["mine","medium"],["quarry","medium"],["extract","medium"],["refine","medium"],["smelt","medium"],
  ["alloy","medium"],["steel","medium"],["iron","medium"],["copper","medium"],["brass","medium"],
  ["bronze","medium"],["aluminum","medium"],["lead","medium"],["zinc","medium"],["silver","medium"],
  ["gold","medium"],["platinum","medium"],["diamond","medium"],["ruby","medium"],["sapphire","medium"],
  ["emerald","medium"],["pearl","medium"],["jewel","medium"],["gem","medium"],["crystal","medium"],

  // HARD: British Spellings, Trap Words & Complex Academic
  ["accommodation","hard"],["archaeology","hard"],["camouflage","hard"],["carbohydrate","hard"],["catastrophe","hard"],
  ["cholesterol","hard"],["choreography","hard"],["chrysanthemum","hard"],["connoisseur","hard"],["euphemism","hard"],
  ["exacerbate","hard"],["lieutenant","hard"],["mayonnaise","hard"],["millennium","hard"],["onomatopoeia","hard"],
  ["paraphernalia","hard"],["picturesque","hard"],["pneumonia","hard"],["pseudonym","hard"],["renaissance","hard"],
  ["repertoire","hard"],["reservoir","hard"],["rhinoceros","hard"],["schizophrenia","hard"],["silhouette","hard"],
  ["stethoscope","hard"],["subterranean","hard"],["veterinarian","hard"],["xylophone","hard"],["bourgeoisie","hard"],
  ["cacophony","hard"],["camaraderie","hard"],["chicanery","hard"],["colloquial","hard"],["conundrum","hard"],
  ["deleterious","hard"],["dichotomy","hard"],["ephemeral","hard"],["epitome","hard"],["facetious","hard"],
  ["fastidious","hard"],["gregarious","hard"],["hegemony","hard"],["iconoclast","hard"],["idiosyncratic","hard"],
  ["juxtapose","hard"],["lackadaisical","hard"],["lethargic","hard"],["lugubrious","hard"],["machiavellian","hard"],
  ["mellifluous","hard"],["mnemonic","hard"],["obfuscate","hard"],["ostentatious","hard"],["panacea","hard"],
  ["paradigm","hard"],["paradox","hard"],["pejorative","hard"],["perfunctory","hard"],["plethora","hard"],
  ["quintessential","hard"],["quixotic","hard"],["serendipity","hard"],["sycophant","hard"],["taciturn","hard"],
  ["ubiquitous","hard"],["vacillate","hard"],["vehement","hard"],["vociferous","hard"],["xenophobia","hard"],
  ["zephyr","hard"],["colour","hard"],["flavour","hard"],["honour","hard"],["labour","hard"],
  ["rumour","hard"],["behaviour","hard"],["humour","hard"],["splendour","hard"],["saviour","hard"],
  ["endeavour","hard"],["armour","hard"],["parlour","hard"],["valour","hard"],["mould","hard"],
  ["smoulder","hard"],["moustache","hard"],["plough","hard"],["draught","hard"],["cheque","hard"],
  ["theatre","hard"],["centre","hard"],["litre","hard"],["metre","hard"],["fibre","hard"],
  ["sombre","hard"],["calibre","hard"],["sepulchre","hard"],["defence","hard"],["offence","hard"],
  ["pretence","hard"],["apologise","hard"],["organise","hard"],["realise","hard"],["recognise","hard"],
  ["analyse","hard"],["paralyse","hard"],["catalyse","hard"],["dialyse","hard"],["travelling","hard"],
  ["cancelling","hard"],["modelling","hard"],["signalling","hard"],["quarrelling","hard"],["fuelling","hard"],
  ["aluminium","hard"],["paediatrics","hard"],["orthopaedics","hard"],["gynaecology","hard"],["foetus","hard"],
  ["anaemia","hard"],["leukaemia","hard"]
].map(([w,d],i)=>({ id:"new_w"+i, word:w, difficulty:d }));
